import path from "node:path";

export const defaultSourceCodeDiscoveryPatterns = [
  "**/*.{js,jsx,ts,tsx,mjs,cjs,mts,cts}",
  "**/*.{py,pyi,pyw}",
  "**/*.{cs,csx,fs,fsx,fsi,vb}",
  "**/*.{java,kt,kts,scala,groovy}",
  "**/*.{c,cc,cpp,cxx,h,hh,hpp,hxx,ixx,inl,tpp}",
  "**/*.{go,rs,zig}",
  "**/*.{lua,rb,php,pl,pm}",
  "**/*.{sql,proto,graphql,gql}",
  "**/*.{sh,bash,zsh,fish,ps1,psm1,psd1}"
] as const;

export const defaultEvidenceDiscoveryPatterns = [
  "**/*.{json,jsonc,yaml,yml,toml,ini,conf,config}",
  "**/*.{log,jsonl,ndjson,out}",
  "**/*.{md,mdx,rst,adoc,txt}",
  "**/.env.example",
  "**/.env.sample",
  "**/.env.template",
  "**/README.md",
  "**/CHANGELOG.md",
  "**/CONTRIBUTING.md",
  "**/ARCHITECTURE.md",
  "**/DECISIONS.md",
  "**/ADR*.md"
] as const;

export const defaultManifestDiscoveryPatterns = [
  "**/package.json",
  "**/package-lock.json",
  "**/pnpm-lock.yaml",
  "**/yarn.lock",
  "**/bun.lockb",
  "**/pyproject.toml",
  "**/requirements*.txt",
  "**/Pipfile",
  "**/Pipfile.lock",
  "**/poetry.lock",
  "**/Cargo.toml",
  "**/Cargo.lock",
  "**/go.mod",
  "**/go.sum",
  "**/*.csproj",
  "**/*.fsproj",
  "**/*.vbproj",
  "**/*.sln",
  "**/pom.xml",
  "**/build.gradle",
  "**/build.gradle.kts",
  "**/settings.gradle",
  "**/settings.gradle.kts",
  "**/gradle.properties",
  "**/CMakeLists.txt",
  "**/*.cmake",
  "**/Makefile",
  "**/GNUmakefile",
  "**/meson.build",
  "**/WORKSPACE",
  "**/WORKSPACE.bazel",
  "**/BUILD",
  "**/BUILD.bazel",
  "**/*.uproject",
  "**/*.uplugin"
] as const;

export const defaultWorkspaceIgnoreDirectories = [
  ".git",
  ".hg",
  ".svn",
  "node_modules",
  "vendor",
  "bower_components",
  "dist",
  "build",
  "coverage",
  ".nyc_output",
  ".next",
  ".nuxt",
  ".svelte-kit",
  ".turbo",
  ".cache",
  ".parcel-cache",
  ".vite",
  ".vercel",
  ".output",
  ".angular",
  ".astro",
  "__pycache__",
  ".pytest_cache",
  ".mypy_cache",
  ".ruff_cache",
  ".tox",
  ".venv",
  "venv",
  ".gradle",
  ".terraform",
  ".serverless",
  ".aws-sam",
  "target",
  "bin",
  "obj",
  "out",
  "tmp",
  "temp",
  ".local-engineering-brain",
  ".codex"
] as const;

export const defaultArchitectureConfigCandidates = [
  ".local-engineering-brain.architecture.json",
  ".local-engineering-brain.architecture.yaml",
  ".local-engineering-brain.architecture.yml",
  "architecture-rules.json",
  "architecture-rules.yaml",
  "architecture-rules.yml"
] as const;

export const defaultGeneratedPatterns = [
  "**/node_modules/**",
  "**/dist/**",
  "**/build/**",
  "**/coverage/**",
  "**/.next/**",
  "**/.nuxt/**",
  "**/.svelte-kit/**",
  "**/.turbo/**",
  "**/vendor/**",
  "**/generated/**",
  "**/__generated__/**",
  "**/.generated/**",
  "**/.openapi-generator/**",
  "**/.swagger-codegen/**",
  "**/prisma/generated/**",
  "**/*.generated.*",
  "**/*.gen.*",
  "**/*.g.*",
  "**/*.designer.*",
  "**/*.pb.*",
  "**/*.grpc.*",
  "**/*.g.cs",
  "**/*.designer.cs",
  "**/*.generated.cs",
  "**/*.generated.h",
  "**/*.generated.cpp",
  "**/*.min.js",
  "**/*.min.css",
  "**/*.map",
  "**/*.snap",
  "**/*.d.ts",
  "**/*.d.mts",
  "**/*.d.cts"
] as const;

export const defaultGeneratedBannerPatterns = [
  /@generated\b/i,
  /\bauto-generated\b/i,
  /\bautomatically generated\b/i,
  /\bgenerated by\b/i,
  /\bdo not edit\b/i,
  /\bdo not modify\b/i
] as const;

export const defaultBinaryExtensions = new Set([
  ".png", ".jpg", ".jpeg", ".gif", ".webp", ".ico", ".bmp", ".tif", ".tiff",
  ".pdf", ".zip", ".gz", ".tar", ".7z", ".rar",
  ".woff", ".woff2", ".ttf", ".otf",
  ".mp3", ".mp4", ".wav", ".ogg", ".mov", ".avi",
  ".dll", ".so", ".dylib", ".exe", ".class"
]);

export const defaultLanguageByExtension: Record<string, string> = {
  ".js": "javascript",
  ".jsx": "javascript",
  ".mjs": "javascript",
  ".cjs": "javascript",
  ".ts": "typescript",
  ".tsx": "typescript",
  ".mts": "typescript",
  ".cts": "typescript",
  ".py": "python",
  ".pyi": "python",
  ".cs": "csharp",
  ".fs": "fsharp",
  ".vb": "vbnet",
  ".java": "java",
  ".kt": "kotlin",
  ".kts": "kotlin",
  ".scala": "scala",
  ".go": "go",
  ".rs": "rust",
  ".c": "c",
  ".cc": "cpp",
  ".cpp": "cpp",
  ".cxx": "cpp",
  ".h": "c",
  ".hpp": "cpp",
  ".hxx": "cpp",
  ".ixx": "cpp",
  ".lua": "lua",
  ".rb": "ruby",
  ".php": "php",
  ".sql": "sql",
  ".proto": "protobuf",
  ".graphql": "graphql",
  ".gql": "graphql",
  ".json": "json",
  ".jsonc": "json",
  ".yaml": "yaml",
  ".yml": "yaml",
  ".toml": "toml",
  ".md": "markdown",
  ".mdx": "markdown",
  ".sh": "shell",
  ".bash": "shell",
  ".zsh": "shell",
  ".fish": "shell",
  ".ps1": "powershell",
  ".psm1": "powershell",
  ".psd1": "powershell"
};

export const defaultTestFilePatterns = [
  "**/*.{test,spec}.{js,jsx,ts,tsx,mjs,cjs,mts,cts}",
  "**/test_*.py",
  "**/*_test.py",
  "**/*_test.go",
  "**/*Test.java",
  "**/*Tests.java",
  "**/*Test.kt",
  "**/*Tests.kt",
  "**/*Test.cs",
  "**/*Tests.cs",
  "**/tests/**/*.rb",
  "**/spec/**/*.rb"
] as const;

export const defaultLogConfigCandidates = [
  ".local-engineering-brain.logs.json",
  ".local-engineering-brain.logs.yaml",
  ".local-engineering-brain.logs.yml",
  "log-intel.json",
  "log-intel.yaml",
  "log-intel.yml"
] as const;

export const defaultWorkspaceLogDiscoveryDirectoryHints = ["logs", "log", "var/log"] as const;
export const defaultWorkspaceLogDiscoveryExtensions = [".log", ".jsonl", ".ndjson", ".out"] as const;
export const defaultWorkspaceLogDiscoveryNamePattern = /(access|error|server|app|api|combined|requests?|runtime|events?)\.(log|txt|jsonl|ndjson|out)$/i;
export const defaultLineLogPattern = /^(\S+)\s+([A-Z]+)\s+([a-zA-Z0-9._-]+)\s+(.*)$/;
export const defaultJsonLogTimestampFields = ["timestamp", "time"] as const;
export const defaultJsonLogLevelFields = ["level", "lvl"] as const;
export const defaultJsonLogServiceFields = ["service", "serviceName"] as const;
export const defaultJsonLogMessageFields = ["message", "msg"] as const;

export const defaultCodeDiscoveryPatterns = [...defaultSourceCodeDiscoveryPatterns] as const;
export const defaultWorkspaceIgnoreEntries = [...defaultWorkspaceIgnoreDirectories] as const;

export function extensionOf(filePath: string): string {
  return path.extname(filePath).toLowerCase();
}
