export const schemaStatements = [
  `PRAGMA journal_mode = WAL;`,
  `PRAGMA busy_timeout = 5000;`,
  `CREATE TABLE IF NOT EXISTS workspaces (
      id TEXT PRIMARY KEY,
      root_path TEXT NOT NULL UNIQUE,
      label TEXT NOT NULL,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL,
      last_indexed_at TEXT
    );`,
  `CREATE TABLE IF NOT EXISTS repositories (
      id TEXT PRIMARY KEY,
      workspace_id TEXT NOT NULL,
      root_path TEXT NOT NULL,
      vcs_type TEXT NOT NULL,
      branch_name TEXT,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL
    );`,
  `CREATE TABLE IF NOT EXISTS packages (
      id TEXT PRIMARY KEY,
      workspace_id TEXT NOT NULL,
      repo_id TEXT NOT NULL,
      name TEXT NOT NULL,
      root_path TEXT NOT NULL,
      manifest_path TEXT NOT NULL,
      package_manager TEXT NOT NULL,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL
    );`,
  `CREATE TABLE IF NOT EXISTS files (
      id TEXT PRIMARY KEY,
      workspace_id TEXT NOT NULL,
      repo_id TEXT NOT NULL,
      package_id TEXT,
      path TEXT NOT NULL UNIQUE,
      language TEXT NOT NULL,
      summary TEXT NOT NULL,
      authored INTEGER NOT NULL,
      hash TEXT NOT NULL,
      updated_at TEXT NOT NULL
    );`,
  `CREATE TABLE IF NOT EXISTS modules (
      id TEXT PRIMARY KEY,
      workspace_id TEXT NOT NULL,
      file_id TEXT NOT NULL,
      package_id TEXT,
      canonical_path TEXT NOT NULL UNIQUE,
      language TEXT NOT NULL,
      summary TEXT NOT NULL,
      public_exports_json TEXT NOT NULL,
      inbound_dependency_count INTEGER NOT NULL DEFAULT 0,
      outbound_dependency_count INTEGER NOT NULL DEFAULT 0,
      updated_at TEXT NOT NULL
    );`,
  `CREATE TABLE IF NOT EXISTS symbols (
      id TEXT PRIMARY KEY,
      workspace_id TEXT NOT NULL,
      module_id TEXT NOT NULL,
      file_id TEXT NOT NULL,
      qualified_name TEXT NOT NULL,
      local_name TEXT NOT NULL,
      kind TEXT NOT NULL,
      signature TEXT,
      exported INTEGER NOT NULL,
      range_start_line INTEGER NOT NULL,
      range_start_column INTEGER NOT NULL,
      range_end_line INTEGER NOT NULL,
      range_end_column INTEGER NOT NULL,
      summary TEXT NOT NULL,
      updated_at TEXT NOT NULL
    );`,
  `CREATE TABLE IF NOT EXISTS commits (
      id TEXT PRIMARY KEY,
      workspace_id TEXT NOT NULL,
      repo_id TEXT NOT NULL,
      sha TEXT NOT NULL UNIQUE,
      author_name TEXT NOT NULL,
      authored_at TEXT NOT NULL,
      summary TEXT NOT NULL,
      branch_name TEXT,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL
    );`,
  `CREATE TABLE IF NOT EXISTS change_groups (
      id TEXT PRIMARY KEY,
      workspace_id TEXT NOT NULL,
      repo_id TEXT NOT NULL,
      branch_name TEXT,
      changed_files_json TEXT NOT NULL,
      source TEXT NOT NULL,
      updated_at TEXT NOT NULL
    );`,
  `CREATE TABLE IF NOT EXISTS architecture_violations (
      id TEXT PRIMARY KEY,
      workspace_id TEXT NOT NULL,
      rule_id TEXT NOT NULL,
      source_module_id TEXT NOT NULL,
      source_path TEXT NOT NULL,
      target_module_id TEXT NOT NULL,
      target_path TEXT NOT NULL,
      severity TEXT NOT NULL,
      explanation TEXT NOT NULL,
      evidence_edge_id TEXT,
      updated_at TEXT NOT NULL
    );`,
  `CREATE TABLE IF NOT EXISTS test_suites (
      id TEXT PRIMARY KEY,
      workspace_id TEXT NOT NULL,
      file_path TEXT NOT NULL,
      framework TEXT NOT NULL,
      name TEXT NOT NULL,
      updated_at TEXT NOT NULL
    );`,
  `CREATE TABLE IF NOT EXISTS test_cases (
      id TEXT PRIMARY KEY,
      workspace_id TEXT NOT NULL,
      suite_id TEXT NOT NULL,
      file_path TEXT NOT NULL,
      name TEXT NOT NULL,
      range_start_line INTEGER NOT NULL,
      range_start_column INTEGER NOT NULL,
      range_end_line INTEGER NOT NULL,
      range_end_column INTEGER NOT NULL,
      updated_at TEXT NOT NULL
    );`,
  `CREATE TABLE IF NOT EXISTS test_results (
      id TEXT PRIMARY KEY,
      workspace_id TEXT NOT NULL,
      test_case_id TEXT NOT NULL,
      status TEXT NOT NULL,
      message TEXT,
      updated_at TEXT NOT NULL
    );`,
  `CREATE TABLE IF NOT EXISTS log_events (
      id TEXT PRIMARY KEY,
      workspace_id TEXT NOT NULL,
      source_name TEXT NOT NULL,
      file_path TEXT NOT NULL,
      service TEXT NOT NULL,
      level TEXT NOT NULL,
      timestamp TEXT NOT NULL,
      message TEXT NOT NULL,
      raw_line TEXT NOT NULL,
      updated_at TEXT NOT NULL
    );`,
  `CREATE TABLE IF NOT EXISTS incidents (
      id TEXT PRIMARY KEY,
      workspace_id TEXT NOT NULL,
      service TEXT NOT NULL,
      title TEXT NOT NULL,
      level TEXT NOT NULL,
      first_seen_at TEXT NOT NULL,
      last_seen_at TEXT NOT NULL,
      event_count INTEGER NOT NULL,
      latest_log_event_id TEXT,
      updated_at TEXT NOT NULL
    );`,
  `CREATE TABLE IF NOT EXISTS edges (
      id TEXT PRIMARY KEY,
      workspace_id TEXT NOT NULL,
      source_id TEXT NOT NULL,
      source_type TEXT NOT NULL,
      target_id TEXT NOT NULL,
      target_type TEXT NOT NULL,
      type TEXT NOT NULL,
      owner_file_path TEXT NOT NULL,
      confidence REAL NOT NULL,
      metadata_json TEXT,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL
    );`,
  `CREATE TABLE IF NOT EXISTS summaries (
      id TEXT PRIMARY KEY,
      workspace_id TEXT NOT NULL,
      entity_id TEXT NOT NULL,
      entity_type TEXT NOT NULL,
      summary TEXT NOT NULL,
      source TEXT NOT NULL,
      updated_at TEXT NOT NULL
    );`,
  `CREATE TABLE IF NOT EXISTS file_hashes (
      workspace_id TEXT NOT NULL,
      path TEXT NOT NULL,
      content_hash TEXT NOT NULL,
      extractor_version TEXT NOT NULL,
      parser_version TEXT NOT NULL,
      updated_at TEXT NOT NULL,
      PRIMARY KEY (workspace_id, path)
    );`,
  `CREATE TABLE IF NOT EXISTS index_jobs (
      id TEXT PRIMARY KEY,
      workspace_id TEXT NOT NULL,
      status TEXT NOT NULL,
      phase TEXT NOT NULL,
      message TEXT NOT NULL,
      files_total INTEGER NOT NULL,
      files_processed INTEGER NOT NULL,
      started_at TEXT NOT NULL,
      finished_at TEXT,
      updated_at TEXT NOT NULL
    );`,
  `CREATE VIRTUAL TABLE IF NOT EXISTS fts_files USING fts5(entity_id UNINDEXED, path, content);`,
  `CREATE VIRTUAL TABLE IF NOT EXISTS fts_symbols USING fts5(entity_id UNINDEXED, qualified_name, local_name, signature, summary);`,
  `CREATE VIRTUAL TABLE IF NOT EXISTS fts_module_summaries USING fts5(entity_id UNINDEXED, canonical_path, summary);`,
  `CREATE VIRTUAL TABLE IF NOT EXISTS fts_logs USING fts5(entity_id UNINDEXED, service, level, message, raw_line);`,
  `CREATE INDEX IF NOT EXISTS idx_files_workspace_path ON files (workspace_id, path);`,
  `CREATE INDEX IF NOT EXISTS idx_modules_workspace_path ON modules (workspace_id, canonical_path);`,
  `CREATE INDEX IF NOT EXISTS idx_symbols_workspace_name ON symbols (workspace_id, local_name, qualified_name);`,
  `CREATE INDEX IF NOT EXISTS idx_commits_workspace_sha ON commits (workspace_id, sha);`,
  `CREATE INDEX IF NOT EXISTS idx_change_groups_workspace_updated ON change_groups (workspace_id, updated_at);`,
  `CREATE INDEX IF NOT EXISTS idx_architecture_violations_workspace ON architecture_violations (workspace_id, severity);`,
  `CREATE INDEX IF NOT EXISTS idx_test_suites_workspace_path ON test_suites (workspace_id, file_path);`,
  `CREATE INDEX IF NOT EXISTS idx_test_cases_workspace_suite ON test_cases (workspace_id, suite_id);`,
  `CREATE INDEX IF NOT EXISTS idx_log_events_workspace_time ON log_events (workspace_id, timestamp DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_log_events_workspace_service ON log_events (workspace_id, service, level);`,
  `CREATE INDEX IF NOT EXISTS idx_incidents_workspace_time ON incidents (workspace_id, last_seen_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_edges_source ON edges (workspace_id, source_id, type);`,
  `CREATE INDEX IF NOT EXISTS idx_edges_target ON edges (workspace_id, target_id, type);`,
  `CREATE INDEX IF NOT EXISTS idx_file_hashes_workspace_path ON file_hashes (workspace_id, path);`,
  `CREATE INDEX IF NOT EXISTS idx_index_jobs_workspace_updated ON index_jobs (workspace_id, updated_at);`
];
